// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../engine/download.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<ProgressEvent> downloadFile({
  required String url,
  required String dest,
  required int numSegments,
}) => RustLib.instance.api.crateApiDownloadDownloadFile(
  url: url,
  dest: dest,
  numSegments: numSegments,
);
