// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'download.freezed.dart';

@freezed
sealed class ProgressEvent with _$ProgressEvent {
  const ProgressEvent._();

  const factory ProgressEvent.started({
    BigInt? totalBytes,
    required BigInt numSegments,
  }) = ProgressEvent_Started;
  const factory ProgressEvent.segmentProgress({
    required BigInt index,
    required BigInt bytesDownloaded,
  }) = ProgressEvent_SegmentProgress;
  const factory ProgressEvent.segmentDone({required BigInt index}) =
      ProgressEvent_SegmentDone;
  const factory ProgressEvent.merged({required BigInt totalBytes}) =
      ProgressEvent_Merged;
}
